# Every day build the lambda function
name: Scheduled Lambda Build

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Setup docker
      - name: Setup context
        run: |
          docker context create builders
      - name: Setup docker
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: builders

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.tjth.co
          method: jwt
          role: go-lambda-image-builder
          secrets: |
                secret/data/container-registry/credentials OCI_USERNAME;
                secret/data/container-registry/credentials OCI_PASSWORD;

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: registry.tjth.co
          username: ${{ steps.import-secrets.outputs.OCI_USERNAME }}
          password: ${{ steps.import-secrets.outputs.OCI_PASSWORD }}

      - name: build image
        run: |
          ./scripts/build.sh
